### ISSUE TITLE
Error 503 Service Unavailble sandbox create user endpoint

### ISSUE THREAD

**Issue by mathiasbanda** [hmrc/api-platform-test-user#41]
Has anyone actually got the create user api to work on the sandbox? I get service Unavailable when I run it on the sandbox, and Unauthorised / permission error 401/403 when I reference the developer hub endpoind.

**Comment by edjannoo** [comment]
I'm told that the issue was that you were attempting to call the application-restricted endpoint without a valid server token and that we have responded to you through the support ticket that you raised. Given that, I will close this issue but please feel free to reopen it if I'm mistaken.
